### ISSUE TITLE
CB2 UR5 Support

### ISSUE THREAD

**Issue by arthur801031** [wuphilipp/gello_software#13]
Hello,

Would `gello_software` support CB2 UR5?  While I was testing the software, I realized that [ur_rtde](https://sdurobotics.gitlab.io/ur_rtde/installation/installation.html) does not support CB2 UR5, which lacks RTDE. Can something like [python-urx](https://github.com/SintefManufacturing/python-urx) be used instead of  [ur_rtde](https://sdurobotics.gitlab.io/ur_rtde/installation/installation.html)?

Here is an excerpt from Universal Robot's [RTDE guide](https://www.universal-robots.com/articles/ur/interface-communication/real-time-data-exchange-rtde-guide/):
> The RTDE is available on CB3/CB3.1 from software 3.4, but specific features may only be available in newer software versions.

Here is an excerpt from [ur_rtde](https://sdurobotics.gitlab.io/ur_rtde/installation/installation.html):
> Compatible Robots
> All CB-Series from CB3/CB3.1 software 3.3
> All e-Series

When I tried to run [ur_rtde](https://sdurobotics.gitlab.io/ur_rtde/installation/installation.html), I got an error message similar to "port 30004 is not opened." And the reason is that the RTDE is available on port number 30004 (specified in the RTDE guide), which CB2 UR5 does not support. 

Thank you!

**Comment by wuphilipp** [comment]
Hi @arthur801031 

It should be pretty strightforward to add support for the UR to use python-urx instead of ur_rtde. I don't have access to CB2 myself right now to test, but happy to help give pointers on what you would need to change to get this to work.

You can use this file as a reference. Essentially you would just need to replace the ur_rdte functions with the corresponding urx ones. 
https://github.com/wuphilipp/gello_software/blob/main/gello/robots/ur.py

For example, instead of 
```
self.robot = rtde_control.RTDEControlInterface(robot_ip)
```

you could do 
```
self.robot = urx.Robot(robot_ip)
```

etc. and continue to replace the rest of the functions.

Let me know if you run into any other issues!
